### ISSUE TITLE
Builder whose data is not consumed in  is left out of execution graph ( Because of bottom up building of graph)

### ISSUE THREAD

**Issue by Kaustavd** [flipkart-incubator/databuilderframework#17]
Builder A produces some dataA 
No other builder have dependency on dataA , neither in consumes, nor in optionals. Because of bottom up graph construction builder A doesn't come in in execution graph.

**Comment by santanusinha** [comment]
This is proper behavior. Put a dependency somewhere. Otherwise it will not
get executed.

----
Upset the established order, and everything becomes chaos. I'm an agent of
chaos. Oh and you know the thing about chaos, it's fair.

**Comment by Kaustavd** [comment]
Is it ideal solution to provide redundant dependency between builder for stitching it together.

**Comment by santanusinha** [comment]
How is it logical to run unrelated builders?

There are several issues involved, when to run it being the least of it. I
recommend not changing this behavior as it goes completely against the
notion of data dependency.

----
Upset the established order, and everything becomes chaos. I'm an agent of
chaos. Oh and you know the thing about chaos, it's fair.
