### ISSUE TITLE
DataDelta content is getting changed if builder is producing the same data that is present in dataDelta.

### ISSUE THREAD

**Issue by ToOnlyGaurav** [flipkart-incubator/databuilderframework#21]
DataDelta is not cloned before passing the data to builders. If the builder produces the same data (that was present in DataDelta) after modification, it will result in changing the dataDelta content as well (as both are having the same reference).

**Comment by santanusinha** [comment]
It can happen if you are modifying the data instead of building it I think.
Will take a look.

**Comment by santanusinha** [comment]
Need more details. Repoen with a testcase please.
