### ISSUE TITLE
DataSet Passed to builder should be  immutable

### ISSUE THREAD

**Issue by Kaustavd** [flipkart-incubator/databuilderframework#31]
One of the primary use case of builder is to do state management of entity which is being represented as data. For this one builder access same data which is being produced by the same. In case builder prematurely exits for some reasons(exceptions) partial commit happens which is not correct. IMO ideally immutable copy should be passed to handle this scenarios

**Comment by santanusinha** [comment]
Immutable copies are really difficult in java as it does not have proper const correctness. A solution would be use cglib type immutable proxies for the data being input in dataset. This would cause potentially serious performance penalties to block against wrong usage and generate a Runtime exception. (It is wrong modelling to modify some data in dataset, a builder should copy and generate new objects, not modify them). Will think about this, but i do not think there is a very clean solution out there.

**Comment by santanusinha** [comment]
Also your data classes should only have final attributes. That way, there is no risk of mutations by others. Serialization and Deserialization of such classes now work fine with jackson either with @JsonProperty annotation in constructor or by using the parameter names module for jackson. This is the only scalable and performant solution to this problem.
